exclude = [
    "__sources",
]

[lint]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "COM", # flake8-commas
    "C",   # pylint-convention
    "E",   # pycodestyle
    "ERA", # flake8-eradicate
    "F",   # pyflakes
    "FIX", # flake8-fixme
    "I",   # isort
    "N",   # pep8-naming
    "PD",  # pandas-vet
    "PIE", # flake8-pie
    "Q",   # flake8-quotes
    "R",   # refactor
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # ruff
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "W",   # warnings
]